# Análise Exploratória de um Dataset de partidas de League of Legends

## 0.1) Import das Bibliotecas

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline
pd.set_option('display.float_format', '{:.2f}'.format)

## 1) Coleta e Limpeza dos Dados

In [4]:
data = pd.read_csv('high_diamond_ranked_10min.csv')
data.head()

,gameId,blueWins,blueWardsPlaced,blueWardsDestroyed,blueFirstBlood,blueKills,blueDeaths,blueAssists,blueEliteMonsters,blueDragons,...,redTowersDestroyed,redTotalGold,redAvgLevel,redTotalExperience,redTotalMinionsKilled,redTotalJungleMinionsKilled,redGoldDiff,redExperienceDiff,redCSPerMin,redGoldPerMin
0,4519157822,0,28,2,1,9,6,11,0,0,...,0,16567,6.80,17047,197,55,-643,8,19.70,1656.70
1,4523371949,0,12,1,0,5,5,5,0,0,...,1,17620,6.80,17438,240,52,2908,1173,24.00,1762.00
2,4521474530,0,15,0,0,7,11,4,1,1,...,0,17285,6.80,17254,203,28,1172,1033,20.30,1728.50
3,4524384067,0,43,1,0,4,5,5,1,0,...,0,16478,7.00,17961,235,47,1321,7,23.50,1647.80
4,4436033771,0,75,4,0,6,6,6,0,0,...,0,17404,7.00,18313,225,67,1004,-230,22.50,1740.40

In [5]:
data.shape

(9879, 40)

In [6]:
# Imprimindo os tipo de todas as colunas do dataframe
for col in data.columns:
    print(f'{col}: {data[col].dtype}', end=" | ")

gameId: int64 | blueWins: int64 | blueWardsPlaced: int64 | blueWardsDestroyed: int64 | blueFirstBlood: int64 | blueKills: int64 | blueDeaths: int64 | blueAssists: int64 | blueEliteMonsters: int64 | blueDragons: int64 | blueHeralds: int64 | blueTowersDestroyed: int64 | blueTotalGold: int64 | blueAvgLevel: float64 | blueTotalExperience: int64 | blueTotalMinionsKilled: int64 | blueTotalJungleMinionsKilled: int64 | blueGoldDiff: int64 | blueExperienceDiff: int64 | blueCSPerMin: float64 | blueGoldPerMin: float64 | redWardsPlaced: int64 | redWardsDestroyed: int64 | redFirstBlood: int64 | redKills: int64 | redDeaths: int64 | redAssists: int64 | redEliteMonsters: int64 | redDragons: int64 | redHeralds: int64 | redTowersDestroyed: int64 | redTotalGold: int64 | redAvgLevel: float64 | redTotalExperience: int64 | redTotalMinionsKilled: int64 | redTotalJungleMinionsKilled: int64 | redGoldDiff: int64 | redExperienceDiff: int64 | redCSPerMin: float64 | redGoldPerMin: float64 |

In [7]:
data.dtypes.unique()

array([dtype('int64'), dtype('float64')], dtype=object)

In [13]:
df_resume_stats = data.describe()

In [42]:
plus_resume_stats = pd.DataFrame(data=[data.skew(), data.kurtosis()], columns=data.kurtosis().index, index=["skew", "kurtosis"])

In [44]:
df_describe_full = pd.concat([df_resume_stats, plus_resume_stats])
df_describe_full

,gameId,blueWins,blueWardsPlaced,blueWardsDestroyed,blueFirstBlood,blueKills,blueDeaths,blueAssists,blueEliteMonsters,blueDragons,...,redTowersDestroyed,redTotalGold,redAvgLevel,redTotalExperience,redTotalMinionsKilled,redTotalJungleMinionsKilled,redGoldDiff,redExperienceDiff,redCSPerMin,redGoldPerMin
count,9879.00,9879.00,9879.00,9879.00,9879.00,9879.00,9879.00,9879.00,9879.00,9879.00,...,9879.00,9879.00,9879.00,9879.00,9879.00,9879.00,9879.00,9879.00,9879.00,9879.00
mean,4500084044.85,0.50,22.29,2.82,0.50,6.18,6.14,6.65,0.55,0.36,...,0.04,16489.04,6.93,17961.73,217.35,51.31,-14.41,33.62,21.73,1648.90
std,27573278.49,0.50,18.02,2.17,0.50,3.01,2.93,4.06,0.63,0.48,...,0.22,1490.89,0.31,1198.58,21.91,10.03,2453.35,1920.37,2.19,149.09
min,4295358071.00,0.00,5.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,11212.00,4.80,10465.00,107.00,4.00,-11467.00,-8348.00,10.70,1121.20
25%,4483301169.00,0.00,14.00,1.00,0.00,4.00,4.00,4.00,0.00,0.00,...,0.00,15427.50,6.80,17209.50,203.00,44.00,-1596.00,-1212.00,20.30,1542.75
50%,4510920346.00,0.00,16.00,3.00,1.00,6.00,6.00,6.00,0.00,0.00,...,0.00,16378.00,7.00,17974.00,218.00,51.00,-14.00,28.00,21.80,1637.80
75%,4521733208.50,1.00,20.00,4.00,1.00,8.00,8.00,9.00,1.00,1.00,...,0.00,17418.50,7.20,18764.50,233.00,57.00,1585.50,1290.50,23.30,1741.85
max,4527990640.00,1.00,250.00,27.00,1.00,22.00,22.00,29.00,2.00,1.00,...,2.00,22732.00,8.20,22269.00,289.00,92.00,10830.00,9333.00,28.90,2273.20
skew,-1.46,0.00,4.14,2.85,-0.02,0.54,0.51,0.89,0.69,0.57,...,5.34,0.41,-0.40,-0.28,-0.29,0.23,-0.03,-0.02,-0.29,0.41
kurtosis,3.33,-2.00,23.44,17.20,-2.00,0.26,0.21,1.16,-0.50,-1.67,...,30.56,0.22,1.24,0.82,0.23,0.42,0.30,0.36,0.23,0.22